version: '2'
services:
  repack:
    image: deezus/repack
    environment:
      RepackSalt: CMK-HjAH4X2Sn!x9%m~D
      RepackDbHost: postgres
      RepackDbPort: 5432
      RepackDbUser: repack
      RepackDbPassword: repack
      RepackDbName: repack
      RepackAdminId: repack
      RepackAdminPassword: repack
    ports:
      - "9999:80"
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: repack
      POSTGRES_PASSWORD: repack
      POSTGRES_DB: repack
    ports:
      - "5432:5432"
    volumes:
      - ".docker/postgres:/var/lib/postgresql/data"
    