version: '2'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: repack
      POSTGRES_PASSWORD: repack
      POSTGRES_DB: repack
    ports:
      - "5432:5432"
    volumes:
      - ".docker/postgres:/var/lib/postgresql/data"
    